export enum ExceptionMessageCode {
  // generals
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  GENERAL_ERROR = 'GENERAL_ERROR',

  // token errors
  TOKEN_ERROR = 'TOKEN_ERROR',
  TOKEN_NOT_BEFORE_ERROR = 'TOKEN_NOT_BEFORE_ERROR',
  TOKEN_EXPIRED_ERROR = 'TOKEN_EXPIRED_ERROR',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_PAYLOAD_MISSING = 'TOKEN_PAYLOAD_MISSING',
  TOKEN_PARAMETER_MISSING = 'TOKEN_PARAMETER_MISSING',
  TOKEN_MISMATCH_ERROR = 'TOKEN_MISMATCH_ERROR',

  ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  FORGOT_PASSWORD_TOKEN_MISSING = 'FORGOT_PASSWORD_TOKEN_MISSING',

  // others
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_OR_PASSWORD_INCORRECT = 'USER_EMAIL_OR_PASSWORD_INCORRECT',
  USER_EMAIL_ALREADY_IN_USE = 'USER_EMAIL_ALREADY_IN_USE',
  USER_ALREADY_IN_CACHE = 'USER_ALREADY_IN_CACHE',
  USERNAME_ALREADY_IN_USE = 'USERNAME_ALREADY_IN_USE',
  SUMMONER_NAME_ALREADY_IN_USE = 'SUMMONER_NAME_ALREADY_IN_USE',
  SUMMONER_NAME_NOT_FOUND = 'SUMMONER_NAME_NOT_FOUND',
  INCORRECT_UUID = 'INCORRECT_UUID',
  REGISTER_CACHE_NOT_FOUND = 'REGISTER_CACHE_NOT_FOUND',
  FORGOT_PASSWORD_CACHE_NOT_FOUND = 'FORGOT_PASSWORD_CACHE_NOT_FOUND',
  PAYPAL_ORDER_ERROR = 'PAYPAL_ORDER_ERROR',
  PAYPAL_PAYMENT_ERROR = 'PAYPAL_PAYMENT_ERROR',
  QUERY_PARAMETER_MISSING = 'QUERY_PARAMETER_MISSING',
  DIVISION_SUMMONER_ERROR = 'DIVISION_SUMMONER_ERROR',
  ONLY_JPEG_ALLOWED = 'ONLY_JPEG_ALLOWED',

  USER_DOESNT_BELONG_TO_CHATHEAD = 'USER_DOESNT_BELONG_TO_CHATHEAD',
  USER_CHATHEAD_PARTNER_NOT_FOUND = 'USER_CHATHEAD_PARTNER_NOT_FOUND',
}
