export enum ExceptionMessageCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  GENERAL_ERROR = 'GENERAL_ERROR',

  // token errors
  TOKEN_ERROR = 'TOKEN_ERROR',
  TOKEN_NOT_BEFORE_ERROR = 'TOKEN_NOT_BEFORE_ERROR',
  TOKEN_EXPIRED_ERROR = 'TOKEN_EXPIRED_ERROR',
}
