export enum ContactUseMessageTypes {
    GENERAL_QUESTION = 'GENERAL_QUESTION',
    APPLICATION_ISSUE = 'APPLICATION_ISSUE',
    ORDER_PROBLEMS = 'ORDER_PROBLEMS',
    REPORT_BUG = 'REPORT_BUG',
    OTHER = 'OTHER',
}
