export enum DuoFinderResponseType {
    DUO_FOUND = 'DUO_FOUND',
    MATCH_FOUND = 'MATCH_FOUND',
    MATCH_FOUND_OTHER = 'MATCH_FOUND_OTHER',

    MATCH_FOUND_BY_SUPERLIKE = 'MATCH_FOUND_BY_SUPERLIKE',
    MATCH_FOUND_OTHER_BY_SUPERLIKE = 'MATCH_FOUND_OTHER_BY_SUPERLIKE',

    MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
    NOBODY_FOUND = 'NOBODY_FOUND',
}

export enum DuoFinderTransferTypes {
    ACCEPT = 'ACCEPT',
    DECLINE = 'DECLINE',
    SUPERLIKE = 'SUPERLIKE',
    JUST_FIND_ANOTHER = 'JUST_FIND_ANOTHER',
}
